#!/usr/bin/env python3
"""
generate_soundbank_header.py — regenerates fm1_control_box/fm1_soundbank_data.h
from the same reference data fm1_soundbank_app/ (this repo's computer-side
CLI tool) uses, so the ESP32-S3 box and the desktop tool never drift apart.

Source of truth:
  ../fm1_soundbank_app/reference/banks/FM-1_factory_128voices_packed.bin  (16384 bytes: 128 x 128-byte packed DX7 voices)
  ../fm1_soundbank_app/reference/presets_provenance.json                  (128 names, factory order)

Output:
  ../fm1_control_box/fm1_soundbank_data.h
    - FACTORY_VOICE_COUNT
    - PRESET_NAMES[128]         display names (trimmed), for the display
    - FACTORY_VOICES[128][128]  raw packed DX7 voice bytes, PROGMEM, for building
                                 a reordered bank dump on-device with no computer
    - CATEGORY_NAMES[13]        one of the 12 named categories, or "PERC/FX"
    - CATEGORY_COLOR565[13]     a distinct RGB565 color per category, for the
                                 round color TFT's category-coded UI
    - CATEGORY_INDEX[128]       which category (0-12) each slot belongs to

Categories are derived from slot position, not stored per-voice: banks 1-3
(slots 000-095) interleave 4 categories every 32 slots (see the FM-1's own
factory naming — e.g. slot 0/1/2/3 = PIANO 1/ORGAN 1/SYN LEAD 1/SYN PAD 1),
confirmed against presets_provenance.json's names below. Bank 4 (096-127) is
percussion/effects with individually kept names, not a 4-way split, so it's
bucketed as one PERC/FX category.

Run this after any change to the reference data in fm1_soundbank_app/.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REF_DIR = HERE.parent / "fm1_soundbank_app" / "reference"
PACKED_FILE = REF_DIR / "banks" / "FM-1_factory_128voices_packed.bin"
PROVENANCE_FILE = REF_DIR / "presets_provenance.json"
OUT_FILE = HERE.parent / "fm1_control_box" / "fm1_soundbank_data.h"

VOICE_LEN = 128

# Category names in the order they appear within banks 1-3 (index 0-11),
# plus bank 4's catch-all. Colors picked for variety + legibility as a
# filled background behind white text on the round TFT.
CATEGORIES = [
    ("PIANO", (255, 180, 60)),
    ("ORGAN", (60, 200, 180)),
    ("SYN LEAD", (255, 70, 130)),
    ("SYN PAD", (150, 120, 255)),
    ("GUITAR", (255, 120, 40)),
    ("DS GUITAR", (230, 60, 60)),
    ("BASS", (60, 90, 220)),
    ("SYN BASS", (50, 200, 220)),
    ("BRASS", (230, 190, 50)),
    ("WOODWIND", (80, 180, 90)),
    ("STRING", (110, 80, 200)),
    ("VOICE", (230, 110, 160)),
    ("PERC/FX", (110, 120, 135)),
]


def rgb565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def category_for_slot(slot):
    bank = slot // 32
    if bank < 3:
        return bank * 4 + (slot % 32) % 4
    return 12  # PERC/FX


def main():
    packed = PACKED_FILE.read_bytes()
    assert len(packed) == 128 * VOICE_LEN, f"unexpected packed size {len(packed)}"

    with open(PROVENANCE_FILE) as f:
        provenance = json.load(f)
    assert len(provenance) == 128

    lines = []
    lines.append("// AUTO-GENERATED by tools/generate_soundbank_header.py — do not hand-edit.")
    lines.append("// Source: fm1_soundbank_app/reference/ (factory order, slot 0 = preset 001 = PIANO 1)")
    lines.append("#pragma once")
    lines.append("#include <Arduino.h>")
    lines.append("")
    lines.append("#define FACTORY_VOICE_COUNT 128")
    lines.append("#define VOICE_LEN 128")
    lines.append("")

    # Names, trimmed for display (DX7 packs names as 10 ASCII chars, space-padded)
    lines.append("static const char* const PRESET_NAMES[FACTORY_VOICE_COUNT] = {")
    for p in provenance:
        name = p["name"].strip()
        escaped = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{escaped}",')
    lines.append("};")
    lines.append("")

    # Packed voice bytes, PROGMEM (16KB total — small next to the ESP32-S3's 4MB flash)
    lines.append("static const uint8_t FACTORY_VOICES[FACTORY_VOICE_COUNT][VOICE_LEN] PROGMEM = {")
    for slot in range(128):
        voice = packed[slot * VOICE_LEN:(slot + 1) * VOICE_LEN]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in voice)
        lines.append(f"  {{ {hex_bytes} }},  // {slot:03d} {provenance[slot]['name'].strip()}")
    lines.append("};")
    lines.append("")

    # Category names + colors
    lines.append(f"#define CATEGORY_COUNT {len(CATEGORIES)}")
    lines.append("static const char* const CATEGORY_NAMES[CATEGORY_COUNT] = {")
    for name, _ in CATEGORIES:
        lines.append(f'  "{name}",')
    lines.append("};")
    lines.append("static const uint16_t CATEGORY_COLOR565[CATEGORY_COUNT] = {")
    for name, rgb in CATEGORIES:
        lines.append(f"  0x{rgb565(rgb):04X},  // {name} rgb{rgb}")
    lines.append("};")
    lines.append("")

    # Per-slot category index, derived from position (see module docstring)
    lines.append("static const uint8_t CATEGORY_INDEX[FACTORY_VOICE_COUNT] PROGMEM = {")
    row = []
    for slot in range(128):
        row.append(str(category_for_slot(slot)))
        if len(row) == 16:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines))
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"Wrote {OUT_FILE} ({size_kb:.0f} KB source; ~16KB in flash as PROGMEM data)")


if __name__ == "__main__":
    main()
